### ISSUE TITLE
Get checksum for * architecture: "HTTP Error 400: Bad Request"

### ISSUE THREAD

**Issue by DmitryRomanenko** [cloudalchemy/ansible-prometheus#138] opened 2018-09-03 12:50 UTC
I have error message when trying to launch this playbook:

> TASK [cloudalchemy.prometheus : Get checksum for amd64 architecture] ***********************************************************************************
fatal: [ci]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'url'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Received HTTP error for https://github.com/prometheus/prometheus/releases/download/v2.3.2/sha256sums.txt : HTTP Error 400: Bad Request"}

When I download this file manually, it's accessible and contains correct data.

I think we need the ability to skip checksum verification.

**Comment by hypery2k** [comment] 2018-10-22 14:38
any chance to get this merged?

**Comment by paulfantom** [comment] 2018-10-22 14:58
Currently there is no working PR resolving this. #142 is not working as expected and I don't have time now to debug that.
I would be happy to review a PR with a proper fix :smile:

**Comment by chrisjohnson00** [comment] 2018-11-11 18:34
Possible related, or possibly not...

````
TASK [ansible-prometheus : Get checksum for amd64 architecture] ****************
objc[3990]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.
objc[3990]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
````


This is run from a mac osx machine (Python 3.7.0), against ubuntu 18.  As part of this, it crashes python on my mac.
I don't encounter this issue run from ubuntu 18 (python 3.6.6) against ubuntu 18.

It seems like it's caused by the lookup by url, as even this fails:

```
- debug:
    msg: "{{ item }}"
  loop: "{{ lookup('url', 'https://github.com/prometheus/prometheus/releases/download/v' + prometheus_version + '/sha256sums.txt', wantlist=True) }}"
```

**Comment by jwhitcraft** [comment] 2019-01-07 19:00
@chrisjohnson00 not sure if you are still running into this issue, but it seems to be an issue with ansible on osx high sierra, see here for a work around: https://github.com/ansible/ansible/issues/32499#issuecomment-341578864

**Comment by chrisjohnson00** [comment] 2019-01-07 20:52
Thanks! I will be sure to include that when running from my Mac!

**Comment by paulfantom** [comment] 2019-11-11 18:55
This issue went stale and it looks like the problem is with ansible itself and not with the role. As a workaround for this PR #239 can be used.

**Closed by paulfantom** 2019-11-11 18:55 UTC
Labels: bug, help wanted
